# Generated by Django 4.2.7 on 2023-12-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='answer',
        ),
    ]
