# Generated by Django 4.2.7 on 2023-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
